from functii_studenti import *

print(suma_cifrelor(123))
print(cmmdc(12, 18))
print(cmmmc(4, 6))
print(numar_divizori(10))
print(lista_prime_pana_la(15))
print(filtreaza_pare([1, 2, 3, 4, 9, 6]))
print(produs_scalar([1, 2], [3, 7]))
print(medie_ponderata([9, 13], [1, 5]))
print(rotire_dreapta([1, 2, 3, 4, 5], 1))
print(interclaseaza([1, 3, 7], [2, 4, 9]))
print(elimina_duplicate([1, 1, 2, 3, 9, 4, 10]))
print(frecventa_litere("abracadabra"))
print(cel_mai_frecvent_cuvant("mere pere mere banane alune piersici"))
print(este_isograma("Paine"))
print(numere_distincte([1, 2, 3, 3]))
print(timp_in_format(3665))
print(parola_valida("pArola12847"))
print(in_binar(10))
print(numar_unic([2, 5, 3, 9, 9]))
print(sunt_anagrame("listen", "silent"))